/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qunar_tc_qmq_store_MmapUtil */

#ifndef _Included_qunar_tc_qmq_store_MmapUtil
#define _Included_qunar_tc_qmq_store_MmapUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qunar_tc_qmq_store_MmapUtil
 * Method:    free0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_qunar_tc_qmq_store_MmapUtil_free0(JNIEnv *, jclass, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif