@startuml

class SendMessageExecutor1 {
    Enum clientType
    String subject
    String partitionName
    String brokerGroup
}

class SendMessageExecutor2 {
}

class SendMessageExecutor3 {
}

OrderedQueueSender -up-> SendMessageExecutor1
OrderedQueueSender -right-> SendMessageExecutor2
OrderedQueueSender -right-> SendMessageExecutor3

SendMessageExecutor1 -[hidden]down-> SendMessageExecutor2
SendMessageExecutor2 -[hidden]down-> SendMessageExecutor3

@enduml